// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240603214921_AlimentarTablaVilla")]
    partial class AlimentarTablaVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "any",
                            Detalle = "Detalle de la villa 1",
                            FechaActualizacion = new DateTime(2024, 6, 3, 16, 49, 21, 54, DateTimeKind.Local).AddTicks(6476),
                            FechaCreacion = new DateTime(2024, 6, 3, 16, 49, 21, 54, DateTimeKind.Local).AddTicks(6462),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Villa 1",
                            Ocupantes = 5,
                            Tarifa = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "any",
                            Detalle = "Detalle de la villa premium",
                            FechaActualizacion = new DateTime(2024, 6, 3, 16, 49, 21, 54, DateTimeKind.Local).AddTicks(6481),
                            FechaCreacion = new DateTime(2024, 6, 3, 16, 49, 21, 54, DateTimeKind.Local).AddTicks(6480),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Premium vista a la playa",
                            Ocupantes = 5,
                            Tarifa = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = "any",
                            Detalle = "Detalle de la villa 3",
                            FechaActualizacion = new DateTime(2024, 6, 3, 16, 49, 21, 54, DateTimeKind.Local).AddTicks(6485),
                            FechaCreacion = new DateTime(2024, 6, 3, 16, 49, 21, 54, DateTimeKind.Local).AddTicks(6484),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Villa 3",
                            Ocupantes = 5,
                            Tarifa = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
